import os

## SERVER
# PATH_TO_FOLDER = '/home/cst/Jixie/source code/unit_forecasting/'
PATH_TO_FOLDER = str(os.getcwd())+'/'
GRAPH_MODEL = 'graph_pakistan_malaysia.pkl'
ETA_MODEL = 'regression_pakistan_malaysia.pkl'
DIST_TO_DIST_GEO_RATIO = 0.9720400077545632
LABEL_ENCODERS = 'label_encoders.pkl'
ONE_HOT_ENCODERS = 'one_hot_encoders.pkl'
SCALER = 'min_max_scaler.pkl'

VERSION = '0.1.0'

RANDOM_STATE = 42


LOCAL_URL = 'http://127.0.0.1:5050/'
HEROKU_URL = 'https://choice-model.herokuapp.com/'
DEV_URL = 'http://office.smarttradzt.com:8080/'

ORIGINAL_FEATURES = ['lat',
 'lon',
 'COURSE',
 'SPEED',
 'HEADING',
 'IMO',
 'A',
 'B',
 'C',
 'D',
 'DRAUGHT',
 'vessel_Year Built',
 'vessel_Length',
 'vessel_Width',
 'vessel_Draught',
 'vessel_Avg Speed',
 'vessel_Max Speed',
 'vessel_Deadweight',
 'vessel_Gross Tonnage',
 'vessel_DRAUGHT_min',
 'vessel_DRAUGHT_mean',
 'vessel_DRAUGHT_median',
 'vessel_DRAUGHT_max',
 'vessel_DRAUGHT_std',
 'vessel_SPEED_min',
 'vessel_SPEED_mean',
 'vessel_SPEED_median',
 'vessel_SPEED_max',
 'vessel_SPEED_std',
 'geohash_1_lat',
 'geohash_1_lon',
 'geohash_2_lat',
 'geohash_2_lon',
 'geohash_3_lat',
 'geohash_3_lon',
 'geohash_4_lat',
 'geohash_4_lon',
 'geohash_5_lat',
 'geohash_5_lon',
 'geohash_6_lat',
 'geohash_6_lon',
 'geohash_7_lat',
 'geohash_7_lon',
 'geohash_8_lat',
 'geohash_8_lon',
 'ais_type_description',
 'month_UTC',
 'drift',
 'navigation_status_description',
 'geohash_1_lat_dest',
 'geohash_1_lon_dest',
 'geohash_2_lat_dest',
 'geohash_2_lon_dest',
 'geohash_3_lat_dest',
 'geohash_3_lon_dest',
 'geohash_4_lat_dest',
 'geohash_4_lon_dest',
 'geohash_5_lat_dest',
 'geohash_5_lon_dest',
 'geohash_6_lat_dest',
 'geohash_6_lon_dest',
 'geohash_7_lat_dest',
 'geohash_7_lon_dest',
 'geohash_8_lat_dest',
 'geohash_8_lon_dest',
 'distance',
 'distance_geohash_3',
 'distance_geohash_4',
 'distance_geohash_5',
 'distance_geohash_6',
 'distance_geohash_7',
 'distance_geohash_8']


FEATURES = ['LATITUDE_scaled',
 'LONGITUDE_scaled',
 'COURSE_scaled',
 'SPEED_scaled',
 'HEADING_scaled',
 'A_scaled',
 'B_scaled',
 'C_scaled',
 'D_scaled',
 'DRAUGHT_scaled',
 'vessel_Year Built_scaled',
 'vessel_Length_scaled',
 'vessel_Width_scaled',
 'vessel_Draught_scaled',
 'vessel_Avg Speed_scaled',
 'vessel_Max Speed_scaled',
 'vessel_Deadweight_scaled',
 'vessel_Gross Tonnage_scaled',
 'vessel_DRAUGHT_min_scaled',
 'vessel_DRAUGHT_mean_scaled',
 'vessel_DRAUGHT_median_scaled',
 'vessel_DRAUGHT_max_scaled',
 'vessel_DRAUGHT_std_scaled',
 'vessel_SPEED_min_scaled',
 'vessel_SPEED_mean_scaled',
 'vessel_SPEED_median_scaled',
 'vessel_SPEED_max_scaled',
 'vessel_SPEED_std_scaled',
 'geohash_1_lat_scaled',
 'geohash_1_lon_scaled',
 'geohash_2_lat_scaled',
 'geohash_2_lon_scaled',
 'geohash_3_lat_scaled',
 'geohash_3_lon_scaled',
 'geohash_4_lat_scaled',
 'geohash_4_lon_scaled',
 'geohash_5_lat_scaled',
 'geohash_5_lon_scaled',
 'geohash_6_lat_scaled',
 'geohash_6_lon_scaled',
 'geohash_7_lat_scaled',
 'geohash_7_lon_scaled',
 'geohash_8_lat_scaled',
 'geohash_8_lon_scaled',
 'month_UTC_scaled',
 'drift_scaled',
 'geohash_1_lat_dest_scaled',
 'geohash_1_lon_dest_scaled',
 'geohash_2_lat_dest_scaled',
 'geohash_2_lon_dest_scaled',
 'geohash_3_lat_dest_scaled',
 'geohash_3_lon_dest_scaled',
 'geohash_4_lat_dest_scaled',
 'geohash_4_lon_dest_scaled',
 'geohash_5_lat_dest_scaled',
 'geohash_5_lon_dest_scaled',
 'geohash_6_lat_dest_scaled',
 'geohash_6_lon_dest_scaled',
 'geohash_7_lat_dest_scaled',
 'geohash_7_lon_dest_scaled',
 'geohash_8_lat_dest_scaled',
 'geohash_8_lon_dest_scaled',
 'distance_scaled',
 'distance_geohash_3_scaled',
 'distance_geohash_4_scaled',
 'distance_geohash_5_scaled',
 'distance_geohash_6_scaled',
 'distance_geohash_7_scaled',
 'distance_geohash_8_scaled',
 'ais_type_description_ais_type_description_100_scaled',
 'ais_type_description_ais_type_description_129_scaled',
 'ais_type_description_ais_type_description_130_scaled',
 'ais_type_description_ais_type_description_132_scaled',
 'ais_type_description_ais_type_description_138_scaled',
 'ais_type_description_ais_type_description_174_scaled',
 'ais_type_description_ais_type_description_22_scaled',
 'ais_type_description_ais_type_description_222_scaled',
 'ais_type_description_ais_type_description_238_scaled',
 'ais_type_description_ais_type_description_29_scaled',
 'ais_type_description_ais_type_description_30_scaled',
 'ais_type_description_ais_type_description_33_scaled',
 'ais_type_description_ais_type_description_36_scaled',
 'ais_type_description_ais_type_description_37_scaled',
 'ais_type_description_ais_type_description_38_scaled',
 'ais_type_description_ais_type_description_52_scaled',
 'ais_type_description_ais_type_description_60_scaled',
 'ais_type_description_ais_type_description_65_scaled',
 'ais_type_description_ais_type_description_70_scaled',
 'ais_type_description_ais_type_description_71_scaled',
 'ais_type_description_ais_type_description_72_scaled',
 'ais_type_description_ais_type_description_73_scaled',
 'ais_type_description_ais_type_description_74_scaled',
 'ais_type_description_ais_type_description_78_scaled',
 'ais_type_description_ais_type_description_79_scaled',
 'ais_type_description_ais_type_description_80_scaled',
 'ais_type_description_ais_type_description_81_scaled',
 'ais_type_description_ais_type_description_82_scaled',
 'ais_type_description_ais_type_description_83_scaled',
 'ais_type_description_ais_type_description_84_scaled',
 'ais_type_description_ais_type_description_85_scaled',
 'ais_type_description_ais_type_description_89_scaled',
 'ais_type_description_ais_type_description_90_scaled',
 'navigation_status_description_At anchor_scaled',
 'navigation_status_description_Constrained by her draught_scaled',
 'navigation_status_description_ENTER_ZONE_scaled',
 'navigation_status_description_EXIT_ZONE_scaled',
 'navigation_status_description_Engaged in Fishing_scaled',
 'navigation_status_description_Moored_scaled',
 'navigation_status_description_Not defined (default)_scaled',
 'navigation_status_description_Not under command_scaled',
 'navigation_status_description_Reserved for future amendment of Navigational Status for HSC_scaled',
 'navigation_status_description_Restricted manoeuverability_scaled',
 'navigation_status_description_Under way sailing_scaled',
 'navigation_status_description_Under way using engine_scaled']

SCALING_FEATURES = ['LATITUDE',
 'LONGITUDE',
 'COURSE',
 'SPEED',
 'HEADING',
 'A',
 'B',
 'C',
 'D',
 'DRAUGHT',
 'vessel_Year Built',
 'vessel_Length',
 'vessel_Width',
 'vessel_Draught',
 'vessel_Avg Speed',
 'vessel_Max Speed',
 'vessel_Deadweight',
 'vessel_Gross Tonnage',
 'vessel_DRAUGHT_min',
 'vessel_DRAUGHT_mean',
 'vessel_DRAUGHT_median',
 'vessel_DRAUGHT_max',
 'vessel_DRAUGHT_std',
 'vessel_SPEED_min',
 'vessel_SPEED_mean',
 'vessel_SPEED_median',
 'vessel_SPEED_max',
 'vessel_SPEED_std',
 'geohash_1_lat',
 'geohash_1_lon',
 'geohash_2_lat',
 'geohash_2_lon',
 'geohash_3_lat',
 'geohash_3_lon',
 'geohash_4_lat',
 'geohash_4_lon',
 'geohash_5_lat',
 'geohash_5_lon',
 'geohash_6_lat',
 'geohash_6_lon',
 'geohash_7_lat',
 'geohash_7_lon',
 'geohash_8_lat',
 'geohash_8_lon',
 'month_UTC',
 'drift',
 'geohash_1_lat_dest',
 'geohash_1_lon_dest',
 'geohash_2_lat_dest',
 'geohash_2_lon_dest',
 'geohash_3_lat_dest',
 'geohash_3_lon_dest',
 'geohash_4_lat_dest',
 'geohash_4_lon_dest',
 'geohash_5_lat_dest',
 'geohash_5_lon_dest',
 'geohash_6_lat_dest',
 'geohash_6_lon_dest',
 'geohash_7_lat_dest',
 'geohash_7_lon_dest',
 'geohash_8_lat_dest',
 'geohash_8_lon_dest',
 'distance',
 'distance_geohash_3',
 'distance_geohash_4',
 'distance_geohash_5',
 'distance_geohash_6',
 'distance_geohash_7',
 'distance_geohash_8',
 'ais_type_description_ais_type_description_100',
 'ais_type_description_ais_type_description_129',
 'ais_type_description_ais_type_description_130',
 'ais_type_description_ais_type_description_132',
 'ais_type_description_ais_type_description_138',
 'ais_type_description_ais_type_description_174',
 'ais_type_description_ais_type_description_22',
 'ais_type_description_ais_type_description_222',
 'ais_type_description_ais_type_description_238',
 'ais_type_description_ais_type_description_29',
 'ais_type_description_ais_type_description_30',
 'ais_type_description_ais_type_description_33',
 'ais_type_description_ais_type_description_36',
 'ais_type_description_ais_type_description_37',
 'ais_type_description_ais_type_description_38',
 'ais_type_description_ais_type_description_52',
 'ais_type_description_ais_type_description_60',
 'ais_type_description_ais_type_description_65',
 'ais_type_description_ais_type_description_70',
 'ais_type_description_ais_type_description_71',
 'ais_type_description_ais_type_description_72',
 'ais_type_description_ais_type_description_73',
 'ais_type_description_ais_type_description_74',
 'ais_type_description_ais_type_description_78',
 'ais_type_description_ais_type_description_79',
 'ais_type_description_ais_type_description_80',
 'ais_type_description_ais_type_description_81',
 'ais_type_description_ais_type_description_82',
 'ais_type_description_ais_type_description_83',
 'ais_type_description_ais_type_description_84',
 'ais_type_description_ais_type_description_85',
 'ais_type_description_ais_type_description_89',
 'ais_type_description_ais_type_description_90',
 'navigation_status_description_At anchor',
 'navigation_status_description_Constrained by her draught',
 'navigation_status_description_ENTER_ZONE',
 'navigation_status_description_EXIT_ZONE',
 'navigation_status_description_Engaged in Fishing',
 'navigation_status_description_Moored',
 'navigation_status_description_Not defined (default)',
 'navigation_status_description_Not under command',
 'navigation_status_description_Reserved for future amendment of Navigational Status for HSC',
 'navigation_status_description_Restricted manoeuverability',
 'navigation_status_description_Under way sailing',
 'navigation_status_description_Under way using engine']